---
title: "GGPLOT2"
output: html_notebook
---

```{r}
library(ggplot2)
```

```{r}
ggplot() + layer(data = diamonds, mapping = aes(x = carat, y = price), geom = "point", stat = "identity")
```

```{r}
ggplot(diamonds, aes(carat, price)) + geom_point() + scale_x_continuous() + scale_y_continuous()
```
```{r}
qplot(carat, price, data = diamonds)
?qplot
```

##n Long-transformed scatterplot of carat and price variables with linear model fitted line
```{r}
ggplot(diamonds, aes(carat, price)) + geom_point() + stat_smooth(method = lm) + scale_x_log10() + scale_y_log10()
```

## Not recommended (deprecated)

```{r}
qplot(carat, price, data = diamonds, geom= c("point", "smooth"), method="lm", log="xy")
```

## Implications: each command works!
```{r}
ggplot(data= diamonds, mapping = aes(price)) + (geom_histogram(stat="bin", position = "identity"))
# OR ggplot(diamonds, aes(x=price)) + geom_histogram()
# qplot(price, data=diamonds, geom="histogram")
```
## Implications: barplot with ploar coordinate!
```{r}
ggplot(diamonds, aes(x = "", fill = clarity))+
  geom_bar(width=1)+
  coord_polar(theta="y")
```

```{r}
ggplot(mpg, aes(x=displ, y=hwy)) + geom_point() + stat_smooth(method="lm", se=FALSE)
```

```{r}
cor(mpg$displ, mpg$hwy)
cor.test(mpg$displ, mpg$hwy)
```
















