---
title: "GGPlot2"
output: html_notebook
---

```{r}
library(ggplot2)
setwd("~/Desktop/r-starter")
```

```{r}
ggplot(data=mpg) +
geom_point(mapping=aes(x=displ, y=hwy)) +
facet_wrap(~class, nrow = 2)
```

```{r}
ggplot(data=mpg) +
geom_point(mapping=aes(x=displ, y=hwy)) +
facet_wrap(drv ~ cyl)
```


```{r}
ggplot(data=mpg) +
geom_point(mapping=aes(x=displ, y=hwy)) +
facet_wrap(drv ~ .)
```

```{r}
ggplot(data=mpg) +
geom_point(mapping=aes(x=displ, y=hwy)) +
facet_wrap(. ~ cyl)
```

```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x=displ, y = hwy))
```

```{r}
mpg
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x=displ, y = hwy, linetype = drv))
```

```{r}
ggplot(data=mpg) +
  geom_point(mapping = aes(x=displ, y = hwy)) +
  geom_smooth(mapping = aes(x=displ, y = hwy))
```
```{r}
ggplot(data=mpg, mapping = aes(x=displ, y = hwy)) +
  geom_point() +
  geom_smooth()
```

```{r}
ggplot(data=mpg, mapping = aes(x=displ, y = hwy)) +
  geom_point(mapping = aes(color=class)) +
  geom_smooth()
```

```{r}
mpg$class = as.factor(mpg$class)
ggplot(data=mpg, mapping = aes(x=displ, y = hwy)) +
  geom_point(mapping = aes(color=class)) +
  geom_smooth(data = filter(mpg, class=="subcompact"), se=FALSE)
# Error in geom_smooth filter, find a fix
?filter
```


```{r}
ggplot(diamonds) +
  stat_count(mapping = aes(x=cut))
```

```{r}
ggplot(diamonds) +
  geom_bar(mapping = aes(x=cut))
```

```{r}
ggplot(diamonds) +
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )
```
```{r}
ggplot(diamonds) +
  geom_bar(mapping = aes(x=cut, colour = cut))
```
```{r}
ggplot(diamonds) +
  geom_bar(mapping = aes(x=cut, fill = cut))
```

```{r}
ggplot(diamonds) +
  geom_bar(mapping = aes(x=cut, fill = clarity))
```
```{r}
ggplot(diamonds) +
  geom_bar(mapping = aes(x=cut, fill = depth))
```

```{r}
ggplot(diamonds, mapping = aes(x=cut, fill=clarity)) +
  geom_bar(alpha = 1/5, position = "identity")
```

```{r}
ggplot(diamonds, mapping = aes(x=cut, color=clarity)) +
  geom_bar(fill = NA, position = "identity")
```

```{r}
ggplot(diamonds) +
  geom_bar( mapping = aes(x=cut, color=clarity), position = "fill")
```

```{r}
ggplot(diamonds) +
  geom_bar( mapping = aes(x=cut, color=clarity), position = "dodge")
```

```{r}
ggplot(mpg, mapping=aes(x = class, y = hwy)) +
  geom_boxplot()
```

```{r}
ggplot(mpg, mapping=aes(x = class, y = hwy)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
nz <- map_data("nz")
ggplot(nz, aes(long, lat, group = group)) +
  geom_point(fill = "white", color = "black")
```

```{r}
library(maps)
nz <- map_data("nz")
ggplot(nz, aes(long, lat, group = group)) +
  geom_point(fill = "white", color = "black") +
  coord_quickmap()
```

```{r}
bar <- ggplot(diamonds) +
  geom_bar(
    mapping = aes(x=cut, fill = cut),
    show.legend = FALSE,
    width = 1
  ) +
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()

bar + coord_polar()
```
















